server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: yrcc-geoserver
  main:
    lazy-initialization: false # 全局懒加载
  mvc:
    path match:
        matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://192.168.1.115:3306/yrcc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  postgis:
    dbtype: "postgis"
    host: "192.168.1.115"
    port: 5432
    database: "gis"
    schema: "public"
    user: "postgres"
    passwd: "postgres"

logging:
  level:
    root: info

geoserver:
  url: "http://192.168.1.115:8080/geoserver"
  username: admin
  password: geoserver
