spring:
  application:
    name: yrcc-geoserver
  mvc:
    path match:
        matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  servlet:
    context-path: /api
  port: 8080

logging:
  level:
    root: info

geoserver:
  url: "http://192.168.1.115:8080/geoserver"
  username: admin
  password: geoserver
